title: TaskBridge Documentation
email: hello@pintsized.dev
description: >- 
  User documentation for TaskBridge.
baseurl: /
url: https://pint-sized.github.io/taskbridge/
repository: pint-sized/taskbridge
github_username:  pint-sized

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-github-metadata
